---
- name: Remove docker
  package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
  register: remove_packages
  retries: 10
  delay: 30
  until: remove_packages is success

- name: disable SELinux
  selinux:
    state: disabled

- name: Add RHEL7 Extras repository
  shell: yum-config-manager --enable "{{ docker_version_map[docker_version]['repo'] }}"
  register: repo_installed
  retries: 10
  delay: 30
  until: repo_installed is success 

- name: Install docker
  package:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    state: present

- name: Verify that fs.may_detach_mounts is enabled
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.may_detach_mounts'
    line: 'fs.may_detach_mounts = 1'
    create: yes
