---
docker_unit_after: "multi-user.target"
docker_storage_driver: overlay2
bootloader_update_command: grub2-mkconfig

# Docker version mapping
docker_version_map:
  "1.13":
    name: 'Docker'
    package: docker-2:1.13.1-109*
    repo: "Red Hat Enterprise Linux*7*Extra*RPMs)"
